using Weaver.Domain;

namespace Weaver.Application.Services;

public interface IWorkItemRecurrenceService
{
    /// <summary>
    /// The work item's repetition, or null if it doesn't repeat. Throws
    /// <see cref="Weaver.Domain.Exceptions.EntityNotFoundException"/> if the work item doesn't exist.
    /// </summary>
    Task<RecurringWorkItem?> GetAsync(Guid workItemId, CancellationToken ct = default);

    /// <summary>Every repeating work item, ordered by work item number.</summary>
    Task<IReadOnlyList<RecurringWorkItem>> ListAsync(CancellationToken ct = default);

    /// <summary>
    /// Makes a work item repeat, or replaces its existing schedule, then immediately creates
    /// any occurrences that fall within the lead window. Items already generated are left as
    /// they are. Rejects an invalid schedule, and rejects repeating an item that was itself
    /// generated by a repetition.
    /// </summary>
    Task<RecurringWorkItem> SetAsync(
        Guid workItemId,
        RecurrenceFrequency frequency,
        IReadOnlyCollection<DayOfWeek> daysOfWeek,
        DateOnly startDate,
        DateOnly? endDate,
        CancellationToken ct = default);

    /// <summary>
    /// Stops a work item repeating. Items it already generated are kept. A no-op if the item
    /// doesn't repeat.
    /// </summary>
    Task RemoveAsync(Guid workItemId, CancellationToken ct = default);

    /// <summary>
    /// Creates every occurrence now within <see cref="WorkItemRecurrence.LeadDays"/> of today,
    /// across all repetitions, including any missed while the server was down. One
    /// repetition failing doesn't stop the others. Returns how many items were created.
    /// </summary>
    Task<int> GenerateDueAsync(CancellationToken ct = default);
}
